### ISSUE TITLE
aot build with angular's ~2.4.5 fail with resolve 'ngx-infinite-scroll/index'

### ISSUE THREAD

**Issue by pulkitnandan** [orizens/ngx-infinite-scroll#175]
This package works well in dev or prod build of angular ~2.4.5 and also the same for version ^4.0.0 which have aot enabled by default in prod build.

But when using with angular ~2.4.5, and that too an aot build, it fails with following error

```
Angular compilation done, starting webpack bundling.
 10% building modules 0/2 modules 2 active ...nfinitescroll/src/main.browser.aot.ts
[at-loader] Using typescript@2.1.6 from typescript and "tsconfig.json" from /home/rohitn/ngxinfinitescroll/tsconfig.webpack.json.

 15% building modules 43/80 modules 37 active ...l/node_modules/@angular/core/index.jsError
    at factoryCallback (/home/rohitn/ngxinfinitescroll/node_modules/webpack/lib/Compilation.js:230:39)
    at /home/rohitn/ngxinfinitescroll/node_modules/webpack/lib/NormalModuleFactory.js:234:19
    at onDoneResolving (/home/rohitn/ngxinfinitescroll/node_modules/webpack/lib/NormalModuleFactory.js:59:20)
    at /home/rohitn/ngxinfinitescroll/node_modules/webpack/lib/NormalModuleFactory.js:126:20
    at /home/rohitn/ngxinfinitescroll/node_modules/webpack/node_modules/async/dist/async.js:3861:9
    at /home/rohitn/ngxinfinitescroll/node_modules/webpack/node_modules/async/dist/async.js:421:16
    at iteratorCallback (/home/rohitn/ngxinfinitescroll/node_modules/webpack/node_modules/async/dist/async.js:996:13)
    at /home/rohitn/ngxinfinitescroll/node_modules/webpack/node_modules/async/dist/async.js:906:16
    at /home/rohitn/ngxinfinitescroll/node_modules/webpack/node_modules/async/dist/async.js:3858:13
    at /home/rohitn/ngxinfinitescroll/node_modules/webpack/lib/NormalModuleFactory.js:121:22
    at onError (/home/rohitn/ngxinfinitescroll/node_modules/enhanced-resolve/lib/Resolver.js:65:10)
    at loggingCallbackWrapper (/home/rohitn/ngxinfinitescroll/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at runAfter (/home/rohitn/ngxinfinitescroll/node_modules/enhanced-resolve/lib/Resolver.js:158:4)
    at innerCallback (/home/rohitn/ngxinfinitescroll/node_modules/enhanced-resolve/lib/Resolver.js:146:3)
    at loggingCallbackWrapper (/home/rohitn/ngxinfinitescroll/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/home/rohitn/ngxinfinitescroll/node_modules/tapable/lib/Tapable.js:234:11)
    at /home/rohitn/ngxinfinitescroll/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:40:4
    at loggingCallbackWrapper (/home/rohitn/ngxinfinitescroll/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at runAfter (/home/rohitn/ngxinfinitescroll/node_modules/enhanced-resolve/lib/Resolver.js:158:4)
    at innerCallback (/home/rohitn/ngxinfinitescroll/node_modules/enhanced-resolve/lib/Resolver.js:146:3)
    at loggingCallbackWrapper (/home/rohitn/ngxinfinitescroll/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/home/rohitn/ngxinfinitescroll/node_modules/tapable/lib/Tapable.js:234:11)
    at innerCallback (/home/rohitn/ngxinfinitescroll/node_modules/enhanced-resolve/lib/Resolver.js:144:11)
    at loggingCallbackWrapper (/home/rohitn/ngxinfinitescroll/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/home/rohitn/ngxinfinitescroll/node_modules/tapable/lib/Tapable.js:231:35)
    at resolver.doResolve.createInnerCallback (/home/rohitn/ngxinfinitescroll/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:44:6)
    at loggingCallbackWrapper (/home/rohitn/ngxinfinitescroll/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at afterInnerCallback (/home/rohitn/ngxinfinitescroll/node_modules/enhanced-resolve/lib/Resolver.js:166:11)
    at loggingCallbackWrapper (/home/rohitn/ngxinfinitescroll/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/home/rohitn/ngxinfinitescroll/node_modules/tapable/lib/Tapable.js:231:35)
resolve 'ngx-infinite-scroll/index' in '/home/rohitn/ngxinfinitescroll/compiled/src/app'
  Parsed request is a module
  using description file: /home/rohitn/ngxinfinitescroll/package.json (relative path: ./compiled/src/app)
  after using description file: /home/rohitn/ngxinfinitescroll/package.json (relative path: ./compiled/src/app)
    resolve as module
      looking for modules in /home/rohitn/ngxinfinitescroll/src
        using description file: /home/rohitn/ngxinfinitescroll/package.json (relative path: ./src)
        after using description file: /home/rohitn/ngxinfinitescroll/package.json (relative path: ./src)
          using description file: /home/rohitn/ngxinfinitescroll/package.json (relative path: ./src/ngx-infinite-scroll/index)
            no extension
              /home/rohitn/ngxinfinitescroll/src/ngx-infinite-scroll/index doesn't exist
            .ts
              /home/rohitn/ngxinfinitescroll/src/ngx-infinite-scroll/index.ts doesn't exist
            .js
              /home/rohitn/ngxinfinitescroll/src/ngx-infinite-scroll/index.js doesn't exist
            .json
              /home/rohitn/ngxinfinitescroll/src/ngx-infinite-scroll/index.json doesn't exist
            as directory
              /home/rohitn/ngxinfinitescroll/src/ngx-infinite-scroll/index doesn't exist
      looking for modules in /home/rohitn/ngxinfinitescroll/node_modules
        using description file: /home/rohitn/ngxinfinitescroll/package.json (relative path: ./node_modules)
        after using description file: /home/rohitn/ngxinfinitescroll/package.json (relative path: ./node_modules)
          using description file: /home/rohitn/ngxinfinitescroll/node_modules/ngx-infinite-scroll/package.json (relative path: ./index)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /home/rohitn/ngxinfinitescroll/node_modules/ngx-infinite-scroll/index doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /home/rohitn/ngxinfinitescroll/node_modules/ngx-infinite-scroll/index.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /home/rohitn/ngxinfinitescroll/node_modules/ngx-infinite-scroll/index.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              /home/rohitn/ngxinfinitescroll/node_modules/ngx-infinite-scroll/index.json doesn't exist
            as directory
              /home/rohitn/ngxinfinitescroll/node_modules/ngx-infinite-scroll/index doesn't exist
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! BugRepro@5.4.1 build:aot:prod: `npm run clean:dist && npm run clean:aot && webpack --config config/webpack.prod.js  --progress --profile --bail`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the BugRepro@5.4.1 build:aot:prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/rohitn/.npm/_logs/2017-07-26T08_20_22_239Z-debug.log

```
I tried fixing it by renaming files from FILE_NAME.d.ts to FILE_NAME.ts as the error suggests, now build succeeds but now it fails @ client browser with error on console as

```
polyfills.883d0c0….bundle.js:1 Uncaught TypeError: u.d is not a constructor
    at t.createInternal (main.a8b6416….bundle.js:1)
    at t.e.create (vendor.104d064….bundle.js:1)
    at t.create (vendor.104d064….bundle.js:1)
    at vendor.104d064….bundle.js:1
    at t.invoke (polyfills.883d0c0….bundle.js:1)
    at Object.onInvoke (vendor.104d064….bundle.js:1)
    at t.invoke (polyfills.883d0c0….bundle.js:1)
    at e.run (polyfills.883d0c0….bundle.js:1)
    at t.run (vendor.104d064….bundle.js:1)
    at e._bootstrapModuleFactoryWithZone (vendor.104d064….bundle.js:1)
    at e.bootstrapModuleFactory (vendor.104d064….bundle.js:1)
    at HTMLDocument.i (main.a8b6416….bundle.js:1)
    at t.invokeTask (polyfills.883d0c0….bundle.js:1)
    at e.runTask (polyfills.883d0c0….bundle.js:1)
    at HTMLDocument.invoke (polyfills.883d0c0….bundle.js:1)
```

where the error line in bundle is `,this._InfiniteScrollModule_6=new u.d,`

**Comment by orizens** [comment]
try using angular2-infinite-scroll

**Comment by orizens** [comment]
ngx-infinite-scroll is angular 4 compatible and above
